### ISSUE TITLE
hotfix-start from support branch adds support branch name to hotfix branch

### ISSUE THREAD

**Issue by vivekmalhotragithub** [aleksandr-m/gitflow-maven-plugin#257] opened 2020-09-22 20:32 UTC
https://github.com/aleksandr-m/gitflow-maven-plugin/blob/717be9068bf681cdd09a92ef3464f3c4dedd779d/src/main/java/com/amashchenko/maven/plugin/gitflow/GitFlowHotfixStartMojo.java#L204-L207

Why we have this logic? 

If I want to create a hotfix branch from an old tag  eg 1.X.0 (not prod branch), then I create support branch support/1.X.0. 
I would still like to have a hotfix branch hotfix/1.X.1 but this logic creates hotfix/support/1.X.0/1.X.1

I am hotfixing via CI server and need control over the name of the hotfix branch.

**Comment by vivekmalhotragithub** [comment] 2020-09-22 21:10
@aleksandr-m  let me know if my PR is ok. Thanks!

**Comment by aleksandr-m** [comment] 2020-09-23 19:21
@vivekmalhotragithub It is so because the hotfix-finish goal needs to know where it should merge hotfix branch.

**Comment by vivekmalhotragithub** [comment] 2020-09-24 07:53
@aleksandr-m what is the correct usage of hotfixing from a tag? I tried these commands but it fails
```
mvn gitflow:hotfix-start --batch-mode  -DpushRemote=true -DfromBranch=support/1.3.0
mvn gitflow:hotfix-finish --batch-mode  -DhotfixVersion=1.3.1
```

The documentation is not explicit about this scenario.

**Comment by vivekmalhotragithub** [comment] 2020-09-24 08:52
Also I felt that hotfix-start should allow creating a hotfix branch from a tag directly rather than creating a support branch first. What do you think about that ?

**Comment by vivekmalhotragithub** [comment] 2020-09-24 20:59
I would also like to know your thoughts on allowing hotfix-start from a tag instead of a branch. This way we don't need support branches.

**Comment by aleksandr-m** [comment] 2020-09-25 05:50
@vivekmalhotragithub What error do you get? 

Where are you going to merge it after, if it is started from the tag?

**Comment by vivekmalhotragithub** [comment] 2020-09-25 22:12
@aleksandr-m so I am running hotfix-start and hotfix-finish in separate CI Jenkins jobs. Consider I am hotfixing from a support branch support/1.11.0
```
mvn gitflow:hotfix-start --batch-mode -DpushRemote=true -DfromBranch=support/1.11.0
```

and later in a separate CI job 
```
mvn gitflow:hotfix-finish --batch-mode  -DhotfixVersion=support/1.11.0/1.11.1
```
Second command fails with error
```
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.14.0:hotfix-finish (default-cli) on project bet-validation-satellite: hotfix-finish: Hotfix branch with name 'hotfix/support/1.11.1/1.11.2' doesn't exist. Cannot finish hotfix. -> [Help 1]
```

The reason i found was hotfix-finish expects that support and hotfix branches are checked out locally which is weird considering i am running on CI server.

Also probably you are right we cannot start a hotfix directly from a tag.

**Comment by aleksandr-m** [comment] 2020-09-27 10:12
Duplicate of #219.

**Closed by aleksandr-m** 2020-09-27 10:12 UTC
