### ISSUE TITLE
How can i update submodules versions

### ISSUE THREAD

**Issue by flod1** [aleksandr-m/gitflow-maven-plugin#90] opened 2018-01-26 08:56 UTC
If there no Paramater for "autoVersionSubmodules" ?
example
mvn release:update-versions -DautoVersionSubmodules=true

**Comment by aleksandr-m** [comment] 2018-01-27 13:35
It should work in most cases out of the box. What is your project structure?

**Comment by flod1** [comment] 2018-05-25 11:37
pom
- submodules1
- submodules2
....

**Comment by aleksandr-m** [comment] 2018-06-06 20:56
Do they have different parent? Different groupId?

**Comment by aleksandr-m** [comment] 2018-07-13 16:59
Seems like duplicate of #48. If not, feel free to reopen with more info.

**Closed by aleksandr-m** 2018-07-13 16:59 UTC
