### ISSUE TITLE
Releasing multi-module project fails on snapshot dependencies

### ISSUE THREAD

**Issue by safiahlberg** [aleksandr-m/gitflow-maven-plugin#180] opened 2019-06-05 06:11 UTC
I just upgraded from 1.10.0 to 1.12.0 and now the release fails due to snapshot dependencies in my multi module build, the snapshots are present in the dependencies betweeen child-modules, but not in external dependencies. 

This seems to have worked (for me) in the 1.10.0 version, but now the behaviour is different?

To clarify:
In level 1 I have the parent pom
In level 2 I have 2 modules, with a dependency on a module in level 3
In level 3 I have 1 module

The dependency on the lvl 3 module is a snapshot dependency, this is how I have understood that dependencies in multi-module project is to be set up.

I may have misunderstood something in Mavens dependency mechanism or how the plugin works.

Or could this be issue #39 that has reappeared?

**Comment by safiahlberg** [comment] 2019-06-05 08:09
Now I have done bisect, and for me, the first rev that causes this problem is 3499b324a8bdd7e1c4b0214b269f183443051196 which closes issue #169

**Comment by aleksandr-m** [comment] 2019-06-05 19:57
@safiahlberg Can you provide some test project to reproduce this issue.

**Comment by safiahlberg** [comment] 2019-06-07 05:34
@aleksandr-m I made a small test project which has the same structure as my production project, but I couldn’t reproduce the error. So it’s not impossible that my production project has a flaw, or maybe I was unable to capture the situation that causes the fault with my test project.

I will look more closely into this and let you know if I find anything suspicious.

**Comment by manderson23** [comment] 2019-06-17 15:24
I think #182 is similar to this.

**Comment by glianeric** [comment] 2019-07-15 15:05
I have just run into the same problem.  I have provided the parameter <useSnapshotInRelease>true</useSnapshotInRelease>, but I'm getting:

build	15-Jul-2019 07:37:13	[WARNING] <artifact>:[inherited] -> Dependency {groupId=x, artifactId=y, version=1.1.21-SNAPSHOT, type=z}

for each module of the multi-module build.

I'll try to build a project to reproduce, but one of the main things that are going on here is a several-level inheritance.  What we have is:

framework-parent-pom (defines all the stuff, including gitflow plugin definition for all of framework)
domain-pom (inherits the framework parent)
multi-module build (inherits the domain-pom)

So I ran with -X and I get release-start configured with:
build	15-Jul-2019 10:31:30	[DEBUG]   (f) useSnapshotInRelease = true
Unfortunately, it seems that this is ignored for module dependencies.

The work-around is to add 'allowSnapshots' as true for release-start, but then we have to split release-start and release-finish (as opposed to running them in the same command) since I don't want to risk having snapshots in a release.

Note:  I'm still testing this part because I've run into another issue with this plugin that has to do with how it runs the maven lifecycle, I think.

**Comment by glianeric** [comment] 2019-07-15 16:36
Further comments:  Splitting release-start and release-finish does not work, both need -DallowSnapshots=true despite the fact that **useSnapshotInRelease**  is provided (inherited through POM hierarchy).

As I understand it, -DallowSnapshots=true is **not** a good work-around as I risk having snapshots in my release.  I have enough controls to live with it for now, but it would be nice to get this fixed.

I'll try to come up with a reasonable test project to fix this.

**Comment by glianeric** [comment] 2019-07-16 13:34
I suggest making the check for snapshots ignore reactor dependencies until after the version is set to release for the modules, just before the release build begins.  At that point it would be correct to check for any snapshots whatsoever.
I note that also I can build with snapshot versions of plugins (they are not checked).

**Comment by manderson23** [comment] 2019-07-17 11:25
Coincidentally the project I reported #182 against may also have had
multiple levels of parent poms but I can't confirm at the moment.

**Comment by aleksandr-m** [comment] 2019-11-03 21:36
Should be fixed by #204.

**Closed by aleksandr-m** 2019-11-03 21:36 UTC
