### ISSUE TITLE
hotfix-start does not increment the correct digit in targetTag

### ISSUE THREAD

**Issue by vivekmalhotragithub** [aleksandr-m/gitflow-maven-plugin#260] opened 2020-09-28 14:22 UTC
when hotfixing latest tag with format A.B.C.D (eg 1.9.0.0) the resultant hotfix branch is 1.9.0.1.
hotfix-start does not provide an option to increment which digit to increment. 

When running this on a CI server we don't know the latest tag for an application.

**Comment by aleksandr-m** [comment] 2021-04-23 19:39
Resolved. Duplicate of #186.

**Closed by aleksandr-m** 2021-04-23 19:39 UTC
