### ISSUE TITLE
Failed post release goal doesn't fail the whole maven build

### ISSUE THREAD

**Issue by thamacher** [aleksandr-m/gitflow-maven-plugin#83] opened 2017-12-18 18:29 UTC
I have defined a post-release-goal with `-DpostReleaseGoals=deploy`. But unfortunately, if the deploy-phase fails for any reason, the maven build-process is marked as successful:

`
18:04:35 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project customer-messaging: Failed to deploy artifacts: Could not transfer artifact XXX:pom:4.49 from/to deploy-release (http://XXXX:8081/nexus/content/repositories/deploy-release/): Failed to transfer file: http://XXX:8081/nexus/content/repositories/deploy-release/XXX/4.49/XXX-4.49.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
18:04:35 [ERROR] 
18:04:35 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
18:04:35 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
18:04:35 [ERROR] 
18:04:35 [ERROR] For more information about the errors and possible solutions, please read the following articles:
18:04:35 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
18:04:35 
18:04:35 	at com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo.executeCommand(AbstractGitFlowMojo.java:963)
18:04:35 	at com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo.executeMvnCommand(AbstractGitFlowMojo.java:905)
18:04:35 	at com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo.mvnRun(AbstractGitFlowMojo.java:851)
18:04:35 	at com.amashchenko.maven.plugin.gitflow.GitFlowReleaseFinishMojo.execute(GitFlowReleaseFinishMojo.java:232)
18:04:35 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
18:04:35 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
18:04:35 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
18:04:35 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
18:04:35 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
18:04:35 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
18:04:35 	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
18:04:35 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
18:04:35 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
18:04:35 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
18:04:35 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
18:04:35 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
18:04:35 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
18:04:35 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:04:35 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:04:35 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:04:35 	at java.lang.reflect.Method.invoke(Method.java:498)
18:04:35 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
18:04:35 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
18:04:35 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
18:04:35 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
18:04:35 [INFO] ------------------------------------------------------------------------
18:04:35 [INFO] Reactor Summary:
18:04:35 [INFO] 
18:04:35 [INFO] XXX ................................ SUCCESS [1:53.070s]
18:04:35 [INFO] XXX ............... SKIPPED
18:04:35 [INFO] XXX .................................... SKIPPED
18:04:35 [INFO] XXX ................................ SKIPPED
18:04:35 [INFO] ------------------------------------------------------------------------
18:04:35 [INFO] BUILD SUCCESS
18:04:35 [INFO] ------------------------------------------------------------------------
18:04:35 [INFO] Total time: 1:54.498s
18:04:35 [INFO] Finished at: Mon Dec 18 18:04:35 UTC 2017
18:04:35 [INFO] Final Memory: 22M/840M
18:04:35 [INFO] ------------------------------------------------------------------------
18:04:35 $ ssh-agent -k
18:04:35 unset SSH_AUTH_SOCK;
18:04:35 unset SSH_AGENT_PID;
18:04:35 echo Agent pid 16790 killed;
18:04:35 [ssh-agent] Stopped.
18:04:35 Recording test results
18:04:35 No emails were triggered.
18:04:35 Finished: SUCCESS
`

**Comment by aleksandr-m** [comment] 2018-01-15 12:20
Duplicate of #80.

**Closed** 2018-01-27 18:14 UTC
Labels: duplicate
