### ISSUE TITLE
More than one release branch exists

### ISSUE THREAD

**Issue by selvasm** [aleksandr-m/gitflow-maven-plugin#308] opened 2021-08-09 12:47 UTC
`Dears,` 

We are working on creation of release and hotbranch. During which we were able to successfully able to create a new release version (0.0.1) using command "mvn gitflow:release-start" and later finished the release branch using "mvn gitflow:release-finish". 

But later when we were  able to create a new release branch for version (0.1.0), using command "mvn gitflow:release-start" , and try to finish the branch creation using "mvn gitflow:release-finish", it fails with error 
_"Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.15.0:release-finish (default-cli) on project mytest release-finish: More than one remote release branch exists. Cannot finish release"_

[INFO] Checking for uncommitted changes.
[DEBUG] git diff --no-ext-diff --ignore-submodules --quiet --exit-code
[DEBUG] git diff-index --cached --quiet --ignore-submodules HEAD --
[DEBUG] git for-each-ref --format="%(refname:short)" refs/heads/release/TM-*
[INFO] Fetching remote branch 'origin '.
[DEBUG] git fetch --quiet origin 
[DEBUG] git for-each-ref --format="%(refname:short)" refs/remotes/origin/release/mytest-*
"origin/release/mytest-0.0.1"
"origin/release/mytest-0.1.0"

Ideally, 

- We should be able to finish a release branch creation, because the previous branch was properly merged to "develop" .
- Also our approach is to have multiple release branch (merged) existing in our repository. 

Could you please help us in achieving the same? Please let know if more information is required. 

Configuration of the plugin.

`<configuration>
    <verbose>true</verbose>
    <commitDevelopmentVersionAtStart>true</commitDevelopmentVersionAtStart>
    <pushRemote>true</pushRemote>
    <fetchRemote>true</fetchRemote>
    <allowSnapshots>true</allowSnapshots>
    <keepBranch>true</keepBranch>
    <versionDigitToIncrement>1</versionDigitToIncrement>
    <skipFeatureVersion>true</skipFeatureVersion>
<configuration> `

**Comment by aleksandr-m** [comment] 2021-09-26 12:11
Duplicate of https://github.com/aleksandr-m/gitflow-maven-plugin/issues/217. Please add additional details there, if any.

**Closed by aleksandr-m** 2021-09-26 12:11 UTC
